## Basic Configuration

baseurl = "http://aiden.nibali.org/"
builddrafts = false
canonifyurls = false
languageCode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Aiden Nibali"
title = "Aiden Nibali"

theme = "hugo-goa"

## Hugo Built-in Features
#disqusShortname = "<yourDisqusShortName>" # Comment out to disable Disqus.
#googleAnalytics = "XYZ"
enableRobotsTXT = true

## Site Settings
[params]
author = "Aiden Nibali"
intro = "Deep learning PhD student"
description = "La Trobe University, Australia"
authorImage = "headshot.jpg"
dateFormat = "Jan 2, 2006"
customCSS = ["css/custom.css"]

## Site Meta Settings
# [params.meta]
# description = "Simple minimalist theme"
# keywords = "minimalist,blog,goa,hugo,developer"

## Social Accounts
[params.social]
github = "anibali"
# instagram = "<username>"
linkedIn = "anibali"
# twitter = "<username>"
# facebook = "<username>"
# google = "<username>"
email = "aiden@nibali.org"

## Extras
[params.extra]
copyright = "© 2016. Aiden Nibali. All rights reserved."
poweredBy = true
highlightJS = true

## Main Menu
[[menu.main]]
name = "blog"
weight = 100
identifier = "blog"
url = "/blog/"
# [[menu.main]]
# name = "about"
# identifier = "about"
# weight = 200
# url = "/about/"
[[menu.main]]
name = "portfolio"
identifier = "portfolio"
weight = 300
url = "/portfolio/"
